CREATE TABLE clientes(
 	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(40) NOT NULL,
    apellido VARCHAR(40) NOT NULL,
    dni INT(11) UNIQUE NOT NULL,
    mail VARCHAR(191) UNIQUE NOT NULL,
    direccion VARCHAR(80) NOT NULL,
    telefono VARCHAR(14) NOT NULL,
    sexo INTEGER UNSIGNED NOT NULL,
    id_provincia INTEGER UNSIGNED NOT NULL,
 	created_at DATETIME,
    updated_at DATETIME,

 	PRIMARY KEY (id),


    FOREIGN KEY (sexo) REFERENCES sexos(id)
	ON UPDATE CASCADE ON DELETE RESTRICT,

    FOREIGN KEY (id_provincia) REFERENCES provincias(id)
	ON UPDATE CASCADE ON DELETE RESTRICT

) ENGINE=InnoDB;
